version: "3.0"
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - "./data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: survey
      MYSQL_DATABASE: survey
      MYSQL_USER: survey
      MYSQL_PASSWORD: survey

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: survey-swagger-ui
    ports:
      - "8081:8080"
    volumes:
      - ./api/swagger:/usr/share/nginx/html/swagger
    environment:
      URLS: "[ {url: 'swagger/v1/catalog.swagger.json', name: 'Catalog'},{ url: 'swagger/v1/user.swagger.json', name: 'User'},{url: 'swagger/v1/answer.swagger.json', name: 'Answer'}]"

  survey-grpc:
    depends_on:
      - db
    image: survey:latest
    links:
      - db
    ports:
      - "8080:8080"
      - "9090:9090"
    entrypoint: "go run main.go -grpc-port=9090 -http-port=8080 -db-host=db -db-user=root -db-password=survey -db-schema=survey"

  survey-web:
    depends_on:
      - db
    image: survey:latest
    links:
      - db
    ports:
      - "80:80"
    working_dir: "/go/src/survey"
    entrypoint: "go run main.go handlers.catalog.go models.catalog.go routes.go"

