// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// AnswerServiceClient is the client API for AnswerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnswerServiceClient interface {
	// Create a new answer
	Create(ctx context.Context, in *AnswerCreateRequest, opts ...grpc.CallOption) (*AnswerCreateResponse, error)
	// Get answer by catalog ID
	View(ctx context.Context, in *AnswerViewRequest, opts ...grpc.CallOption) (*AnswerViewResponse, error)
	// Get all answers
	ViewAll(ctx context.Context, in *AnswerViewAllRequest, opts ...grpc.CallOption) (*AnswerViewAllResponse, error)
}

type answerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnswerServiceClient(cc grpc.ClientConnInterface) AnswerServiceClient {
	return &answerServiceClient{cc}
}

func (c *answerServiceClient) Create(ctx context.Context, in *AnswerCreateRequest, opts ...grpc.CallOption) (*AnswerCreateResponse, error) {
	out := new(AnswerCreateResponse)
	err := c.cc.Invoke(ctx, "/v1.AnswerService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *answerServiceClient) View(ctx context.Context, in *AnswerViewRequest, opts ...grpc.CallOption) (*AnswerViewResponse, error) {
	out := new(AnswerViewResponse)
	err := c.cc.Invoke(ctx, "/v1.AnswerService/View", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *answerServiceClient) ViewAll(ctx context.Context, in *AnswerViewAllRequest, opts ...grpc.CallOption) (*AnswerViewAllResponse, error) {
	out := new(AnswerViewAllResponse)
	err := c.cc.Invoke(ctx, "/v1.AnswerService/ViewAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnswerServiceServer is the server API for AnswerService service.
// All implementations must embed UnimplementedAnswerServiceServer
// for forward compatibility
type AnswerServiceServer interface {
	// Create a new answer
	Create(context.Context, *AnswerCreateRequest) (*AnswerCreateResponse, error)
	// Get answer by catalog ID
	View(context.Context, *AnswerViewRequest) (*AnswerViewResponse, error)
	// Get all answers
	ViewAll(context.Context, *AnswerViewAllRequest) (*AnswerViewAllResponse, error)
	mustEmbedUnimplementedAnswerServiceServer()
}

// UnimplementedAnswerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAnswerServiceServer struct {
}

func (UnimplementedAnswerServiceServer) Create(context.Context, *AnswerCreateRequest) (*AnswerCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedAnswerServiceServer) View(context.Context, *AnswerViewRequest) (*AnswerViewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method View not implemented")
}
func (UnimplementedAnswerServiceServer) ViewAll(context.Context, *AnswerViewAllRequest) (*AnswerViewAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ViewAll not implemented")
}
func (UnimplementedAnswerServiceServer) mustEmbedUnimplementedAnswerServiceServer() {}

// UnsafeAnswerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnswerServiceServer will
// result in compilation errors.
type UnsafeAnswerServiceServer interface {
	mustEmbedUnimplementedAnswerServiceServer()
}

func RegisterAnswerServiceServer(s grpc.ServiceRegistrar, srv AnswerServiceServer) {
	s.RegisterService(&_AnswerService_serviceDesc, srv)
}

func _AnswerService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnswerCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnswerServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.AnswerService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnswerServiceServer).Create(ctx, req.(*AnswerCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnswerService_View_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnswerViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnswerServiceServer).View(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.AnswerService/View",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnswerServiceServer).View(ctx, req.(*AnswerViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnswerService_ViewAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnswerViewAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnswerServiceServer).ViewAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.AnswerService/ViewAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnswerServiceServer).ViewAll(ctx, req.(*AnswerViewAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AnswerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.AnswerService",
	HandlerType: (*AnswerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _AnswerService_Create_Handler,
		},
		{
			MethodName: "View",
			Handler:    _AnswerService_View_Handler,
		},
		{
			MethodName: "ViewAll",
			Handler:    _AnswerService_ViewAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "answer.proto",
}
